name: VisualAI
channels:
  - pytorch
  - defaults
dependencies:
  - abseil-cpp=20230802.0=h313beb8_2
  - aiohttp=3.9.5=py311h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=14.0.2=hc7aafb3_1
  - attrs=23.1.0=py311hca03da5_0
  - aws-c-auth=0.6.19=h80987f9_0
  - aws-c-cal=0.5.20=h80987f9_0
  - aws-c-common=0.8.5=h80987f9_0
  - aws-c-compression=0.2.16=h80987f9_0
  - aws-c-event-stream=0.2.15=h313beb8_0
  - aws-c-http=0.6.25=h80987f9_0
  - aws-c-io=0.13.10=h80987f9_0
  - aws-c-mqtt=0.7.13=h80987f9_0
  - aws-c-s3=0.1.51=h80987f9_0
  - aws-c-sdkutils=0.1.6=h80987f9_0
  - aws-checksums=0.1.13=h80987f9_0
  - aws-crt-cpp=0.18.16=h313beb8_0
  - aws-sdk-cpp=1.10.55=h313beb8_0
  - blas=1.0=openblas
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py311h313beb8_8
  - bzip2=1.0.8=h80987f9_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.3.11=hca03da5_0
  - certifi=2024.6.2=py311hca03da5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cpuonly=2.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=2.19.1=py311hca03da5_0
  - dill=0.3.8=py311hca03da5_0
  - filelock=3.13.1=py311hca03da5_0
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.4.0=py311h80987f9_0
  - fsspec=2024.3.1=py311hca03da5_0
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - grpc-cpp=1.48.2=hc60591f_4
  - gtest=1.14.0=h48ca7d4_1
  - huggingface_hub=0.23.1=py311hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - jinja2=3.1.4=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libssh2=1.11.0=h3e2b118_0
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib=3.8.4=py311hca03da5_0
  - matplotlib-base=3.8.4=py311h7aedaa7_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - multidict=6.0.4=py311h80987f9_0
  - multiprocess=0.70.15=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.2.1=py311hca03da5_0
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.14=h80987f9_0
  - orc=1.7.4=hdca1487_1
  - packaging=23.2=py311hca03da5_0
  - pandas=2.2.2=py311h7aedaa7_0
  - pillow=10.3.0=py311h80987f9_0
  - pip=23.3.1=py311hca03da5_0
  - pyarrow=14.0.2=py311ha07b5f9_0
  - pyparsing=3.0.9=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.9=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h80987f9_1
  - pytorch=2.3.1=py3.11_0
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.2=py311hca03da5_0
  - setuptools=68.2.2=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h313beb8_1
  - sqlite=3.41.2=h80987f9_0
  - sympy=1.12=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - torchaudio=2.3.1=py311_cpu
  - torchvision=0.18.1=py311_cpu
  - tornado=6.3.3=py311h80987f9_0
  - tqdm=4.66.2=py311hb6e6a13_0
  - typing-extensions=4.11.0=py311hca03da5_0
  - typing_extensions=4.11.0=py311hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - urllib3=2.2.2=py311hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wheel=0.41.2=py311hca03da5_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.9.3=py311h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - opencv-contrib-python==4.9.0.80
prefix: /opt/anaconda3/envs/VisualAI
